### ISSUE TITLE
Feature Request: Extend "Conditional Logic" instead adding "Conditional Logic Advanced" field

### ISSUE THREAD

**Issue by tyrann0us** [andrejpavlovic/acf-conditional-logic-advanced#1]
Hi @andrejpavlovic,
great plugin, thank you for your work!

I was wondering if it's possible to extend the native "Conditional Logic" field/dropdown instead of adding a new "Conditional Logic Advanced" field? _I haven't checked ACF's nor your plugins's code so bear with me if there are technical reasons which prevent this._

Thanks!

**Comment by andrejpavlovic** [comment]
It's been a while since I've put this plugin together, but I don't think it was possible to extend the native "Conditional Logic". One option was to try to copy/duplicate existing "Conditional Logic" and then add the extra functionality, but then I would have to maintain the old logic and the newly added one. Instead, I decided to leave the old "Conditional Logic" as is, and add the extra logic as a separate setting.

I know, it's not ideal, but then there is less duplicated code and less code to maintain overall.

**Comment by tyrann0us** [comment]
Thanks for getting back to me so quickly.

@elliotcondon recently announced a major rework of the conditional logic (see https://github.com/AdvancedCustomFields/acf-field-type-template/issues/35#issuecomment-306956052 et seq.) so when this is done hopefully it will be possible to extend it.
